# Generated by Django 3.0.8 on 2020-07-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200613_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('overview', models.TextField()),
                ('popularity', models.IntegerField(verbose_name='popularities')),
                ('vote_count', models.IntegerField()),
                ('poster_path', models.CharField(max_length=400)),
                ('vote_average', models.IntegerField()),
            ],
        ),
    ]
