# Generated by Django 3.0.8 on 2020-07-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
